version: "3"
services:
  app:
    container_name: node-cakes-app
    restart: always
    build: .
    ports:
      - "3001:3001"
    external_links:
      - mongo
    volumes: ["./:/usr/src/app"]
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
